version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: pytest
  deploy:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to production
          command: |
            ssh user@server "mkdir -p /opt/my-python-app"
            rsync -azP . user@server:/opt/my-python-app/

